### ISSUE TITLE
more explanation needed 

### ISSUE THREAD

**Issue by Mohamed-94** [sidihamady/SLALOM#1]
Hi, Dr.sidihamadi 
Thanks for droping this amazing project on github.
i like your project so i stars/watch it..
i'm really interested in your research ..i have read the guide and it was amazing..
But i think you need to update the README with more information and -especially- pictures, so every one can understand the conceptes easily.

Thank you again

Best

**Comment by sidihamady** [comment]
Thank you for your interest in the project and your valuable comment. We will update the software with more explanation as soon as possible.
Best regards
